apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On 
spec:
  rules:
  - host: jorge.guerrero.com
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 8080